name: Deploy Blog
# 触发条件
on:
  #1. 手动触发
  workflow_dispatch:

  #2. 自动触发:每次推送代码到主分支触发
  push:
    branches:
      - main

jobs:
  deploy:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && contains(github.event.head_commit.message, '[deploy]'))
    runs-on: ubuntu-latest
    steps:
      - name: Run remote script via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/html
            git pull
            npm install
            npm run build
            npm run start
